### ISSUE TITLE
Spanish translation for the entire documentation

### ISSUE THREAD

**Issue by michaelizer** [androm3da/llvm-doc#1]
Greetings,

I would love to contribute to the project with the Spanish translation, primarily to help Spanish speakers understand and get involved into it. Spanish is my native language so don't panic. I work for the Utopian.io community. I suggest (in case you accept) creating a new branch for every different language, let me know what do you think and I'll come up with more detailed suggestions about it.

Thanks in advance for your time.

**Comment by androm3da** [comment]
Apologies, I don't know how I missed this issue, @michaelizer .  There's no need or usefulness for translating this repo.

This repository is an unmonitored/unattended repo just for mirroring an upstream repository: https://github.com/llvm-mirror/llvm
